#!/bin/bash
clear
url=$1
echo "All-in-one Download Script for Termux"
echo "----------Last updated Jun 18 2020----------"
echo "--------------------------------------------"
echo "1: Download with youtube-dl"
echo "2: Download with ffmpeg(m3u8/m3u)"
echo "3: Download with wget (Recursive)"
echo "4: Download with spotdl (Spotify All-in-one)"
echo "5: Download with youtube-dl and extract audio"
echo "6: Download with gallery-dl"
echo "Default: Download with youtube-dl"
read n
if [ "$n" == '2' ]; then
echo "Output Filename:"
read name
ffmpeg -i "$url" -c copy -bsf:a aac_adtstoasc /storage/emulated/0/Downloads/"$name"
else
if [ "$n" == '3' ]; then
wget -P "/storage/emulated/0/Downloads/" -c --mirror  --recursive --no-clobber  --page-requisites --html-extension --convert-links -e robots=off --restrict-file-names=windows --no-parent "$url"
else
if [ "$n" == '4' ]; then 
[ ! -d "/storage/emulated/0/Downloads/spotdl" ] && mkdir "/storage/emulated/0/Downloads/spotdl"
test -f  "./.spotdl_playlist"  && rm "./.spotdl_playlist.txt"
test -f  "./.spotdl_album"  && rm "./.spotdl_album.txt"
[[ $url == *"track"* ]] && spotdl --output-file "/storage/emulated/0/Downloads/spotdl/{artist} - {track-name}.{output-ext}" --song "$url" -q best --output-ext mp3
[[ $url == *"playlist"* ]] && spotdl --playlist "$url" --write-to  "./.spotdl_playlist.txt"  && spotdl --output-file "/storage/emulated/0/Downloads/spotdl/{artist} - {track-name}.{output-ext}" --list "./.spotdl_playlist.txt" -q best --output-ext mp3 && rm -f "./.spotdl_playlist.txt"
[[ $url == *"album"* ]] && spotdl --album "$url" --write-to  "./.spotdl_album.txt" && spotdl --output-file "/storage/emulated/0/Downloads/spotdl/{artist} - {track-name}.{output-ext}" --list "./.spotdl_album.txt" -q best --output-ext mp3 && rm -f "./.spotdl_album.txt"
else
if [ "$n" == '5' ]; then
[ ! -d "/storage/emulated/0/Downloads/youtube-dl" ] && mkdir "/storage/emulated/0/Downloads/youtube-dl"
youtube-dl -x --embed-thumbnail --audio-format mp3 -f bestaudio --audio-quality 0 -c -i "$url" --cookies  ~/cookies -o "/storage/emulated/0/Downloads/youtube-dl/%(title)s.%(ext)s"
else
if [ "$n" == '6' ]; then
[ ! -d "/storage/emulated/0/Downloads/gallery-dl" ] && mkdir "/storage/emulated/0/Downloads/gallery-dl"
gallery-dl "$url" --dest "/storage/emulated/0/Downloads/gallery-dl/"
else
[ ! -d "/storage/emulated/0/Downloads/youtube-dl" ] && mkdir "/storage/emulated/0/Downloads/youtube-dl"
youtube-dl -c -i "$url" --cookies  ~/cookies -o "/storage/emulated/0/Downloads/youtube-dl/%(title)s.%(ext)s"
fi
fi
fi
fi

